name: Check and Test

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    env:
      MPLBACKEND: "agg"
      DISABLE_COVERAGE: true
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: refs/heads/${{ github.head_ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pipenv
      run: |
        python3 -m pip install --upgrade pip
        pip install pipenv
    - name: Install dependencies
      run: |
        pipenv install --skip-lock --dev
    - name: Lint with flake8
      run: |
        pipenv run flake8 niapy tests scent.py setup.py
    - name: Check codestyle
      run: |
        pipenv run pycodestyle niapy tests scent.py setup.py --config=.pycodestyle.ini
    - name: Check docstyle
      run: |
        pipenv run pydocstyle niapy tests scent.py setup.py
    - name: Run incremental tests
      env:
        TESTMON_DATAFILE: config/testmondata/${{ matrix.os }}_${{ matrix.python-version }}
      run: |
        echo "${TESTMON_DATAFILE}"
        pipenv run pytest --testmon -ra -vv --random --random-seed=32786 niapy tests
        status=$?
        if [ $status -eq 1 ] || [ $status -eq 5 ]; then exit 0; else exit $status; fi
    - name: Add and commit updated .testmondata file
      if: matrix.python-version == '3.9' # this prevents multiple updates in the same run (we only run this step on ubuntu-latest with python 3.9)
      run: |
        git config --local user.email "niapy.organization+NiaPy[bot]@gmail.com"
        git config --local user.name "NiaPy[bot]"
        git add --force .testmondata
        git commit -m "Update .testmondata"
    - name: Push updated .testmon file
      if: matrix.python-version == '3.9' # this prevents multiple updates in the same run (we only run this step on ubuntu-latest with python 3.9)
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
        force: false
        
  